import type { ExpenseSimulationFormErrors } from '../../types'
import { formatCurrency } from '../../utils/financialAnalysisPresentation'

type Props = { description: string; totalAmount: string; installments: string; errors: ExpenseSimulationFormErrors; onChange: (field: 'expenseDescription' | 'totalAmount' | 'installments', value: string) => void }

export function NewExpenseSection({ description, totalAmount, installments, errors, onChange }: Props) {
  const monthlyAmount = Number(totalAmount) > 0 && Number(installments) >= 1 ? Number(totalAmount) / Number(installments) : 0
  return <section className="form-section" aria-labelledby="new-expense-title"><div className="form-section-heading"><div><span className="step-number">5</span><h2 id="new-expense-title">Nova despesa</h2></div><p>Descreva a compra que deseja simular.</p></div><div className="new-expense-fields"><div className="field-group"><label htmlFor="expenseDescription">Descrição</label><input id="expenseDescription" value={description} aria-invalid={Boolean(errors.expenseDescription)} aria-describedby={errors.expenseDescription ? 'expenseDescription-error' : undefined} onChange={(event) => onChange('expenseDescription', event.target.value)} />{errors.expenseDescription && <span className="field-error" id="expenseDescription-error">{errors.expenseDescription}</span>}</div><div className="field-group"><label htmlFor="totalAmount">Valor total</label><div className="money-input"><span aria-hidden="true">R$</span><input id="totalAmount" type="number" min="0.01" step="0.01" inputMode="decimal" value={totalAmount} aria-invalid={Boolean(errors.totalAmount)} aria-describedby={errors.totalAmount ? 'totalAmount-error' : undefined} onChange={(event) => onChange('totalAmount', event.target.value)} /></div>{errors.totalAmount && <span className="field-error" id="totalAmount-error">{errors.totalAmount}</span>}</div><div className="field-group"><label htmlFor="installments">Quantidade de parcelas</label><input id="installments" type="number" min="1" max="72" step="1" inputMode="numeric" value={installments} aria-invalid={Boolean(errors.installments)} aria-describedby={errors.installments ? 'installments-error' : undefined} onChange={(event) => onChange('installments', event.target.value)} />{errors.installments && <span className="field-error" id="installments-error">{errors.installments}</span>}</div></div><p className="installment-preview" aria-live="polite"><span>Valor mensal estimado apenas para apresentação</span><strong>{formatCurrency(monthlyAmount)}</strong></p></section>
}
